import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import Comprimento from '../../components/Comprimento'
import Volume from '../../components/Volume';
import Temperatura from '../../components/Temperatura';

export default function Numeros() {

  const [type, setType]= useState(0);

  function tipo (valor){
    setType(valor);
  }
  return (
    <div className='container'>
      <Head>
        <title>Conversor de unidades</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          <div className="btn-group" role="group" aria-label="Basic mixed styles example">
            <button type="button" className={type===0?'bnt border rounded-start btn-primary':"btn rounded-start border"} onClick={()=>{tipo(0)}}>Comprimento</button>
            <button type="button" className={type===1?'bnt border btn-primary':"btn border"} onClick={()=>{tipo(1)}}>Volume</button>
            <button type="button" className={type===2?'bnt border rounded-end btn-primary':"btn rounded-end border"} onClick={()=>{tipo(2)}}>Temperatura</button>
          </div>
          {
            type===0&&<Comprimento />
          }{
            type===1&& <Volume />
          }
          {
            type===2&& <Temperatura />
          }
          
        </div>
    </div>
  )
}
