import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, {useState} from 'react';

 function ConverterText() {
  
  const [text, setText] = React.useState('');
  const pattern = /^[0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*$/
  

  //console.log(text)

  function capitalize() {
    let newStr = []
    if (text !=''){
      const letras = text.split('\n');
      let palavras = letras.join(' ');
      //console.log(palavras)
      const arr = letras

      for (let i = 0; i < arr.length; i++){// verifica todas as palavras
        if(arr[i].charAt(0)=='\n'){newStr.push('\n')}
        if(pattern.test(arr[i].charAt(0))){ //verificar o primeiro caractere se é número ou simbolo 
          newStr.push(arr[i].charAt(0)+arr[i].substring(1).toLowerCase());
        } else { //verificar o primeiro caractere e altera o primeiro para maiúsculo
          newStr.push(arr[i].charAt(0).toUpperCase()+arr[i].substring(1).toLowerCase());
        }
      }

      setText(newStr.join(' '));

    }else {
      alert('Favor entrar com o texto');
    }
  }

  function toTitleCase() {
    let newStr = [];
    if (text !=''){
      const arr = text.split(' ');

      for (let i = 0; i < arr.length; i++){// verifica todas as palavras

        if(pattern.test(arr[i].charAt(0))){ //verificar o primeiro caractere se é número ou simbolo 
          newStr.push(arr[i].charAt(0)+arr[i].substring(1).toLowerCase());
        } else { //verificar o primeiro caractere e altera o primeiro para maiúsculo
          newStr.push(arr[i].charAt(0).toUpperCase()+arr[i].substring(1).toLowerCase());
        }
      }

      setText(newStr.join(' '));

    }else {
      alert('Favor entrar com o texto');
    }
  }

  function toUpper() {

    if (text !=''){
      const arr = text.split(' ');
      console.log(arr.length);
      let newStr = []
      
      let letra = '';
      for (let i = 0; i < arr.length; i++){// verifica todas as palavras
        let newStrSolo = [];
        for (let j = 0; j < arr[i].length; j++){
          //console.log(pattern.test(arr[i].charAt(j)));
          if(pattern.test(arr[i].charAt(j))){
            newStrSolo.push(arr[i].charAt(j));
          }else{
            letra = arr[i].charAt(j);
            newStrSolo.push(arr[i].charAt(j).toUpperCase());
            //console.log(arr[i].charAt(j).toUpperCase());
          }
        }
        newStr.push(newStrSolo.join(''));
        console.log(newStr);
      }
      setText(newStr.join(' '));
      
    }else {
      alert('Favor entrar com o texto');
    }
  } 
  function toLower() {

    if (text !=''){
      const arr = text.split(' ');
      console.log(arr.length);
      let newStr = [];
      
      let letra = '';
      for (let i = 0; i < arr.length; i++){// verifica todas as palavras
        let newStrSolo = [];
        for (let j = 0; j < arr[i].length; j++){
          //console.log(pattern.test(arr[i].charAt(j)));
          if(pattern.test(arr[i].charAt(j))){
            newStrSolo.push(arr[i].charAt(j));
          }else{
            letra = arr[i].charAt(j);
            newStrSolo.push(arr[i].charAt(j).toLowerCase());
            //console.log(arr[i].charAt(j).toUpperCase());
          }
        }
        newStr.push(newStrSolo.join(''));
        console.log(newStr);
      }
      setText(newStr.join(' '));
      
    }else {
      alert('Favor entrar com o texto');
    }
  }
  function alternating() {

    if (text !=''){
      //const arr = text.split(' ');
      //console.log(arr.length);
      let newStr = [];
      
      let letra = '';
      for (let i = 0; i < text.length; i++){// verifica todas as palavras
        if(i%2===1){
          letra=letra+(text.charAt(i).toUpperCase())
        }else{
          letra=letra+(text.charAt(i).toLowerCase())
        }
      }
      setText(letra); 
    }else {
      alert('Favor entrar com o texto');
    }
  }

  function inverse() {

    if (text !=''){
      //const arr = text.split(' ');
      //console.log(arr.length);
      let newStr = [];
      
      let letra = '';
      for (let i = 0; i < text.length; i++){// verifica todas as palavras
        if(/[A-ZÁÀÂÃÉÈÊÍÏÓÔÕÖÚÜÇÑ]/.test(text.charAt(i))){
          letra=letra+(text.charAt(i).toLowerCase())
        }else {
          letra=letra+(text.charAt(i).toUpperCase())
        }
      }
      setText(letra); 
    }else {
      alert('Favor entrar com o texto');
    }
  }

  return (
    <div className='container'>
      <Head>
        <title>Conversores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <h3>Acidentalmente deixou o Caps Lock do teclado ligado e escreveu algo, e não quer escrever tudo de novo?</h3>
        <p>Insira o seu texto e escolha para que tipo de formato deseja converter.</p>
        <form className='form-floating ms-1'>
            <textarea 
            className='form-control textarea' 
            placeholder="Leave a comment here" 
            id="floatingTextarea" 
            type="text" 
            value={text}
            onChange={e => setText(e.target.value)}
            />
            <label className="floatingTextarea">Digite o seu Texto aqui</label>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={capitalize}>Formato de frase</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={toUpper}>MAIÚSCULAS</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={toLower}>minúsculas</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={toTitleCase} >Formato Maiúsculas</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={alternating} >fOrMaTo aLtErNaDo</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={inverse} >Inverter</button>
        </form>
      </main>
    </div>
  )
}

export default ConverterText