import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, {useState} from 'react';

 function ConverterText() {
  
  const [text, setText] = React.useState('');
  const pattern = /^[0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*$/
  

  console.log(text)

  function capitalize() {
    let newStr = []
    if (text !=''){
      const arr = text.split(' ')
      console.log(arr)
      for (let i = 0; i < arr.length; i++){// verifica todas as palavras

        if(pattern.test(arr[i].charAt(0))){ //verificar o primeiro caractere se é número ou simbolo 
          newStr.push(arr[i].charAt(0)+arr[i].substring(1).toLowerCase())
        } else { //verificar o primeiro caractere e altera o primeiro para maiúsculo
          newStr.push(arr[i].charAt(0).toUpperCase()+arr[i].substring(1).toLowerCase())
        }
      }

      setText(newStr.join(' '))

    }else {
      alert('Favor entrar com o texto')
    }
  }

  function toTitleCase() {
    let newStr = []
    if (text !=''){
      const arr = text.split(' ')

      for (let i = 0; i < arr.length; i++){// verifica todas as palavras

        if(pattern.test(arr[i].charAt(0))){ //verificar o primeiro caractere se é número ou simbolo 
          newStr.push(arr[i].charAt(0)+arr[i].substring(1).toLowerCase())
        } else { //verificar o primeiro caractere e altera o primeiro para maiúsculo
          newStr.push(arr[i].charAt(0).toUpperCase()+arr[i].substring(1).toLowerCase())
        }
      }

      setText(newStr.join(' '))

    }else {
      alert('Favor entrar com o texto')
    }
  }

  function toUpper() {

    if (text !=''){
      const arr = text.split(' ')
      console.log(arr.length)
      let newStr = []
      
      let letra = ''
      for (let i = 0; i < arr.length; i++){// verifica todas as palavras
        let newStrSolo = []
        for (let j = 0; j < arr[i].length; j++){
          //console.log(pattern.test(arr[i].charAt(j)))
          if(pattern.test(arr[i].charAt(j))){
            newStrSolo.push(arr[i].charAt(j))
          }else{
            letra = arr[i].charAt(j)
            newStrSolo.push(arr[i].charAt(j).toUpperCase())
            //console.log(arr[i].charAt(j).toUpperCase())
          }
        }
        newStr.push(newStrSolo.join(''))
        console.log(newStr)
      }
      setText(newStr.join(' '))
      
    }else {
      alert('Favor entrar com o texto')
    }
  } 

  return (
    <div className='container'>
      <Head>
        <title>Conversores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <h3>Accidentally left the caps lock on and typed something, but can not be bothered to start again and retype it all?</h3>
        <p>Simply enter your text and choose the case you want to convert it to.</p>
        <form className='form-floating ms-1'>
            <textarea 
            className='form-control textarea' 
            placeholder="Leave a comment here" 
            id="floatingTextarea" 
            rows="5"
            type="text" 
            value={text}
            onChange={e => setText(e.target.value)}
            />
            <label className="floatingTextarea">Digite o seu Texto aqui</label>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={toTitleCase}>Sentence case</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={toUpper}>UPPER CASE</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={capitalize}>Capitalize</button>
            <button type="button" className="btn btn-outline-primary mt-2 me-2 " onClick={toTitleCase} >Title Case</button>
        </form>
      </main>
    </div>
  )
}

export default ConverterText