import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Conversores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>

        <div className="row g-5">
          <div className="col-md-6">
            <h2>Conversores</h2>
            <p>Simples conversor</p>
            <ul className="icon-list ps-0">
              <li className="d-flex align-items-start mb-1"><a href="./Texto">Conversores de texto</a></li>
              <li className="d-flex align-items-start mb-1"><a href="./Unidades">Conversores de unidades de Comprimento</a></li>
              <li className="text-muted d-flex align-items-start mb-1">Conversores de unidades de Volume (coming soon!)</li>
            </ul>
          </div>

          <div className="col-md-6">
            <h2></h2>
            <p></p>
            <ul className="icon-list ps-0">
              <li className="d-flex align-items-start mb-1"><p></p></li>
              <li className="d-flex align-items-start mb-1"><p></p></li>
              <li className="d-flex align-items-start mb-1"><p></p></li>
              <li className="d-flex align-items-start mb-1"><p></p></li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}
